#pragma once

#define FONT_ICON_FILE_NAME_FA "fontawesome-webfont.ttf"

#define ICON_TOASTER_CAMERA				u8"\uf030"
#define ICON_TOASTER_ARROWS_ALT			u8"\uf0b2"
#define ICON_TOASTER_CUBE				u8"\uf1b2"
#define ICON_TOASTER_SUN_O				u8"\uf185"
#define ICON_TOASTER_CODE				u8"\uf121"
#define ICON_TOASTER_GLOBE				u8"\uf0ac"
#define ICON_TOASTER_CLOUD				u8"\uf0c2"
#define ICON_TOASTER_COG				u8"\uf013"
#define ICON_TOASTER_BINOCULARS			u8"\uf1e5"
#define ICON_TOASTER_SITEMAP			u8"\uf0e8"
#define ICON_TOASTER_GAMEPAD			u8"\uf11b"
#define ICON_TOASTER_EXCLAMATION_CIRCLE u8"\uf06a"
#define ICON_TOASTER_PAINT_BRUSH		u8"\uf1fc"
#define ICON_TOASTER_CALCULATOR			u8"\uf1ec"
#define ICON_TOASTER_WRENCH				u8"\uf0ad"
#define ICON_TOASTER_FOLDER				u8"\uf07b"
#define ICON_TOASTER_PAUSE				u8"\uf04c"
#define ICON_TOASTER_PLAY				u8"\uf04b"
#define ICON_TOASTER_TRASH_O			u8"\uf014"
#define ICON_TOASTER_CIRCLE_O			u8"\uf10c"
#define ICON_TOASTER_HAND_ROCK_O		u8"\uf255"
#define ICON_TOASTER_SQUARE_O			u8"\uf096"